# Generated by Django 6.0.7 on 2026-07-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="is_paused",
            field=models.BooleanField(default=False),
        ),
    ]
