# Generated by Django 6.0.7 on 2026-08-02 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_website_is_paused"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="website",
            constraint=models.UniqueConstraint(
                fields=("owner", "url"), name="unique_website_per_user"
            ),
        ),
    ]
