# Generated by Django 6.0.7 on 2026-08-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0003_website_unique_website_per_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuscheck",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="statuscheck",
            index=models.Index(
                fields=["website", "-timestamp"], name="monitor_sta_website_f7a5c1_idx"
            ),
        ),
    ]
