# Generated by Django 6.0.7 on 2026-08-05 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0004_alter_statuscheck_timestamp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="website",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="website",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="websites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
