# Generated by Django 6.0.7 on 2026-08-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0005_alter_website_options_alter_website_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="timer",
            field=models.PositiveBigIntegerField(
                default=60, help_text="Time interval in seconds between checks."
            ),
        ),
    ]
